### ISSUE TITLE
File input/upload

### ISSUE THREAD

**Issue by S1SYPHOS** [sirfuzzalot/textual-inputs#37]
Hey there,
First of all: this plugin looks / works great!

I'd like to see a field acting on file drag/drop / input, when using the current text field, this results in all path characters being inserted after one another 😀 

What do you think? Could this be something worth it?

**Comment by sirfuzzalot** [comment]
@S1SYPHOS apologies for the extreme delay. I had to step away from my open source work for a while.

I'm glad you like the inputs :smile:  and I think you're idea of drag and drop support for File Paths is interesting. The underlying Textual framework has come a long way since this request and since this inputs project was started. It filled a gap in the framework, which was largely read only at the time. I'd encourage you to see what the Textual docs (which are pretty detailed now) have to offer for this or similar solutions. Best of luck :four_leaf_clover: on your projects.

Textual now supports inputs natively -> https://textual.textualize.io/widgets/input/

**Comment by S1SYPHOS** [comment]
Yeah they're doing a very fine job over there, thanks for your reply! 🙂
